//! All reply codes as specified by [RFC959](https://datatracker.ietf.org/doc/html/rfc959).

use strum_macros::FromRepr;

#[derive(Ord, PartialOrd, Eq, PartialEq, Debug, Copy, Clone, FromRepr)]
#[repr(u16)]
pub(crate) enum ReplyCode {
  RestartMarkerReply = 110,
  ServiceReadyInNNNMinutes = 120,
  DataConnectionAlreadyOpen = 125,
  FileStatusOkay = 150,
  CommandOkay = 200,
  CommandNotImplementedSuperfluous = 202,
  SystemStatus = 211,
  DirectoryStatus = 212,
  FileStatus = 213,
  Help = 214,
  NameSystemType = 215,
  ServiceReady = 220,
  ClosingControlConnection = 221,
  DataConnectionOpen = 225,
  ClosingDataConnection = 226,
  EnteringPassiveMode = 227,
  UserLoggedIn = 230,
  RequestedFileActionOkay = 250,
  PathnameCreated = 257,
  UserNameOkay = 331,
  NeedAccountForLogin = 332,
  RequestedFileActionPendingFurtherInformation = 350,
  ServiceNotAvailableClosingControlConnection = 421,
  CantOpenDataConnection = 425,
  ConnectionClosedTransferAborted = 426,
  AuthNotAvailable = 431,
  RequestedFileActionNotTaken = 450,
  RequestedActionAborted = 451,
  InsufficientStorageSpace = 452,
  SyntaxErrorCommandUnrecognized = 500,
  SyntaxErrorInParametersOrArguments = 501,
  CommandNotImplemented = 502,
  BadSequenceOfCommands = 503,
  CommandNotImplementedForThatParameter = 504,
  NotLoggedIn = 530,
  NeedAccountForStoringFiles = 532,
  RequestDeniedForPolicyReasons = 534,
  ProtectionLevelNotSupported = 536,
  FileUnavailable = 550,
  RequestedActionAbortedPageTypeUnknown = 551,
  RequestedFileActionAbortedExceededStorage = 552,
  RequestedActionNotTakenFileNameNotAllowed = 553,
}
